apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981564654508:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-120VTVVVOW26W
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::981564654508:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
        - system:masters

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-12T14:47:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "840"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 62ad5b5b-6470-11ea-af12-027fb1b39996
