apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981564654508:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8F11ZOWR9XZ5
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::981564654508:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
        - system:masters

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-11T15:21:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "817"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f6664820-63ab-11ea-b873-0a65d3253522
