apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981564654508:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MRFYATX48709
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::981564654508:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
        - system:masters

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-12T17:44:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "760"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 31d570f9-6489-11ea-bf92-0ebd8fdb1362
